### ISSUE TITLE
remark-attr dependency (^0.6.2) incompatible with Node v6

### ISSUE THREAD

**Issue by medwards81** [shooontan/gatsby-remark-attr#3]
When you have a chance, can you make the pull request to upgrade your dependent remark-attr package to use the latest version (^0.8.0)? I am stuck running an older version of node (v6.11) on a production machine and cannot upgrade for the foreseeable future, and when building the gatsby site am getting an error at line 177 of node_module/remark-attr/index.js (^0.6.2), specifically the use of unsupported spread operators in objects. 

The newer version of remark-attr should fix this issue, as it appears to bypass the use of spread operators. I'm running node v8 on my local machine, and everything works great, but am unfortunately stuck with a lower version of node on the production machine.

**Comment by shooontan** [comment]
I published gatsby-remark-attr v0.0.2 which depends remark-attr v0.8.0.
Please install latest gatsby-remark-attr.

**Comment by medwards81** [comment]
Thank you! Appreciate the quick response, and everything now works perfectly.
